### ISSUE TITLE
Upgrade bundle to support grails 2.0.0

### ISSUE THREAD

**Issue by krimple** [textmate/groovy-grails.tmbundle#3]
Is it possible to either upgrade this bundle or fork it to support 2.0.0 of grails?

**Comment by ldaley** [comment]
What's not working for you?

**Comment by krimple** [comment]
I thought grails 2.0 added new commands and features.

Sent from my iPhone

On Jan 20, 2012, at 4:43 PM, Luke Daley
reply@reply.github.com
wrote:

**Comment by infininight** [comment]
Closing due to lack of specific feature requests, etc.
