### ISSUE TITLE
Issue with syntax highlighting of embedded groovy

### ISSUE THREAD

**Issue by wondersloth** [textmate/groovy-grails.tmbundle#5]
<g:set var="relativePercent" value="${ Math.round( (source.percent / maxPercent) * 100 ) }"/>

Doesn't syntax highlight correctly it breaks on the / ... / coloring it read and making it look like regex for JS.

**Comment by infininight** [comment]
Please include code samples when you report issues with the syntax highlighting.

**Comment by wondersloth** [comment]
```
<div class="swatch" style="background-color: ${swatchHexColor}">
    <g:set var="relativePercent" value="${ Math.round( (source.percent / maxPercent) * 100 ) }"/>
</div>

```

Using a slash `(source.percent / maxPercent)` to do that division will cause it to break. Any subsequent markup will lose highlighting.

**Comment by infininight** [comment]
The issue was actually in the Groovy bundle, fix noted above.
